import { useMemo, useRef } from 'react';
import type { CommandItem } from '../../components/CommandPalette';
import { createAppCommands } from '../appCommands';
import type { AppCommandContext } from '../appCommands';

export function useAppCommandRegistry(context: AppCommandContext): CommandItem[] {
  const contextRef = useRef(context);
  contextRef.current = context;

  return useMemo(() => createAppCommands({
    formatCapabilities: context.formatCapabilities,
    outlineOpen: context.outlineOpen,
    focusMode: context.focusMode,
    themeMode: context.themeMode,
    currentVisualStyleLabel: context.currentVisualStyleLabel,
    pasteReviewHunks: context.pasteReviewHunks,
    missingCitationCount: context.missingCitationCount,
    missingVariableCount: context.missingVariableCount,
    structuredContextAvailable: context.structuredContextAvailable,
    structuredTableSampleAvailable: context.structuredTableSampleAvailable,
    structuredPasteBackValidationAvailable: context.structuredPasteBackValidationAvailable,
    recentPreviews: context.recentPreviews,
    headings: context.headings,
    onNew: () => contextRef.current.onNew(),
    onOpen: () => contextRef.current.onOpen(),
    onOpenFolder: () => contextRef.current.onOpenFolder(),
    onSave: () => contextRef.current.onSave(),
    onSaveAs: () => contextRef.current.onSaveAs(),
    onFind: () => contextRef.current.onFind(),
    onOpenSlashMenu: () => contextRef.current.onOpenSlashMenu(),
    onOpenTemplates: () => contextRef.current.onOpenTemplates(),
    onOpenSettings: () => contextRef.current.onOpenSettings(),
    onOpenTutorial: () => contextRef.current.onOpenTutorial(),
    onOpenFullTutorial: () => contextRef.current.onOpenFullTutorial(),
    onInsertImage: () => contextRef.current.onInsertImage(),
    onInsertCitation: () => contextRef.current.onInsertCitation(),
    onInsertMermaid: () => contextRef.current.onInsertMermaid(),
    onInsertSvgFigure: () => contextRef.current.onInsertSvgFigure(),
    onInsertVariable: () => contextRef.current.onInsertVariable(),
    onCheckExternalTools: () => contextRef.current.onCheckExternalTools(),
    onCheckInkscape: () => contextRef.current.onCheckInkscape(),
    onSetInkscapePath: () => contextRef.current.onSetInkscapePath(),
    onInsertProtectedBlock: () => contextRef.current.onInsertProtectedBlock(),
    onInsertEditorComment: () => contextRef.current.onInsertEditorComment(),
    onInsertHumanEditorComment: () => contextRef.current.onInsertHumanEditorComment(),
    onInsertTargetedInstruction: () => contextRef.current.onInsertTargetedInstruction(),
    onInsertVariantGroup: () => contextRef.current.onInsertVariantGroup(),
    onReloadBibliography: () => contextRef.current.onReloadBibliography(),
    onSyncBibliography: () => contextRef.current.onSyncBibliography(),
    onInsertReferencesDirective: () => contextRef.current.onInsertReferencesDirective(),
    onApplyScientificTypography: () => contextRef.current.onApplyScientificTypography(),
    onGenerateSubmissionReadiness: () => contextRef.current.onGenerateSubmissionReadiness(),
    onCopyScieMDLlmSkill: () => contextRef.current.onCopyScieMDLlmSkill(),
    onGenerateScieMDLlmSkill: () => contextRef.current.onGenerateScieMDLlmSkill(),
    onCopyStructuredContext: () => contextRef.current.onCopyStructuredContext(),
    onCopySelectedStructureContext: () => contextRef.current.onCopySelectedStructureContext(),
    onCopyParserDiagnostics: () => contextRef.current.onCopyParserDiagnostics(),
    onCopyStructuredSchemaSummary: () => contextRef.current.onCopyStructuredSchemaSummary(),
    onCopyStructuredTableSample: () => contextRef.current.onCopyStructuredTableSample(),
    onCopyStructuredHealthReport: () => contextRef.current.onCopyStructuredHealthReport(),
    onCopyRedactedStructuredPreview: () => contextRef.current.onCopyRedactedStructuredPreview(),
    onValidateStructuredClipboard: () => contextRef.current.onValidateStructuredClipboard(),
    onCopyRichText: () => contextRef.current.onCopyRichText(),
    onExportHtml: () => contextRef.current.onExportHtml(),
    onExportPandoc: (format) => contextRef.current.onExportPandoc(format),
    onPrintPreview: () => contextRef.current.onPrintPreview(),
    onOpenPasteReview: () => contextRef.current.onOpenPasteReview(),
    onToggleOutline: () => contextRef.current.onToggleOutline(),
    onToggleFocusMode: () => contextRef.current.onToggleFocusMode(),
    onSidebarOutline: () => contextRef.current.onSidebarOutline(),
    onSidebarFiles: () => contextRef.current.onSidebarFiles(),
    onSidebarReferences: () => contextRef.current.onSidebarReferences(),
    onSidebarData: () => contextRef.current.onSidebarData(),
    onCycleTheme: () => contextRef.current.onCycleTheme(),
    onCycleVisualStyle: () => contextRef.current.onCycleVisualStyle(),
    onSetVisualStyle: (style) => contextRef.current.onSetVisualStyle(style),
    onIncreaseFont: () => contextRef.current.onIncreaseFont(),
    onDecreaseFont: () => contextRef.current.onDecreaseFont(),
    onShowShortcuts: () => contextRef.current.onShowShortcuts(),
    onShowAbout: () => contextRef.current.onShowAbout(),
    onOpenRecent: (path) => contextRef.current.onOpenRecent(path),
    onJumpToHeading: (heading) => contextRef.current.onJumpToHeading(heading),
    onNewFromTemplate: (template) => contextRef.current.onNewFromTemplate(template),
  }), [
    context.outlineOpen,
    context.formatCapabilities,
    context.focusMode,
    context.themeMode,
    context.currentVisualStyleLabel,
    context.pasteReviewHunks,
    context.missingCitationCount,
    context.missingVariableCount,
    context.structuredContextAvailable,
    context.structuredTableSampleAvailable,
    context.structuredPasteBackValidationAvailable,
    context.recentPreviews,
    context.headings,
  ]);
}
