export interface RoundTripGoldenFixture {
  name: string;
  markdown: string;
  preservedSnippets: string[];
  expectedValidationCodes?: string[];
}

export const roundTripGoldenCorpus: RoundTripGoldenFixture[] = [
  {
    name: 'scientific-paper-surface',
    markdown: [
      '---',
      'title: Round Trip Study',
      'bibliography: refs.bib',
      'variables:',
      '  sample_count: 42',
      '---',
      '',
      '# Abstract',
      '',
      'We studied {{ sample_count }} samples with [@smith2026] and report $p < 0.05$.',
      '',
      '<!-- scie_md:lock:start reason="approved result" -->',
      'The primary result is locked before submission.',
      '<!-- scie_md:lock:end -->',
      '',
      '<!-- scie_md:note id="llm-1" kind="llm" target="quote" quote="primary result": Check statistical wording. -->',
      '<!-- scie_md:instruction target="next-block" prompt="Keep terminology precise" -->',
      'The primary result should stay linked to the note above.',
      '',
      '<!-- scie_md:variant:group id="abstract" active="short" -->',
      '<!-- scie_md:variant:item id="full" name="Full abstract" -->',
      'Full abstract text.',
      '<!-- scie_md:variant:item id="short" name="Short abstract" -->',
      'Short abstract text.',
      '<!-- scie_md:variant:end -->',
      '',
      ':::callout {#callout-method}',
      'Method detail with reference to @fig-workflow.',
      ':::',
      '',
      ':::result {#result-main}',
      'Result block content that should remain editable.',
      ':::',
      '',
      ':::figure {#fig-workflow}',
      '```mermaid',
      'flowchart LR',
      '  Sample --> Analysis',
      '```',
      '',
      'Workflow diagram.',
      ':::',
      '',
      '| Metric | Value |',
      '| --- | ---: |',
      '| Accuracy | 0.98 |',
      '',
      '```svg',
      '<svg viewBox="0 0 100 40"><text x="4" y="22">Vector</text></svg>',
      '```',
      '',
      'Footnote evidence remains attached.[^evidence]',
      '',
      '[^evidence]: Evidence note with continuation text.',
    ].join('\n'),
    preservedSnippets: [
      '{{ sample_count }}',
      '[@smith2026]',
      '$p < 0.05$',
      '<!-- scie_md:lock:start reason="approved result" -->',
      '<!-- scie_md:note id="llm-1" kind="llm" target="quote" quote="primary result": Check statistical wording. -->',
      '<!-- scie_md:instruction target="next-block" prompt="Keep terminology precise" -->',
      '<!-- scie_md:variant:group id="abstract" active="short" -->',
      ':::callout {#callout-method}',
      ':::result {#result-main}',
      ':::figure {#fig-workflow}',
      '```mermaid',
      'flowchart LR',
      '```svg',
      'Accuracy',
      '0.98',
      '[^evidence]:',
    ],
  },
  {
    name: 'source-preserved-raw-html-and-unknown-directive',
    markdown: [
      '# Source Preserved',
      '',
      '<section data-role="supplement">Raw HTML stays raw.</section>',
      '',
      ':::unknown-block {#custom-review}',
      'A future extension owns this block.',
      ':::',
    ].join('\n'),
    preservedSnippets: [
      '<section data-role="supplement">Raw HTML stays raw.</section>',
      ':::unknown-block {#custom-review}',
      'A future extension owns this block.',
    ],
    expectedValidationCodes: ['raw-html', 'directive-unknown-visual'],
  },
];

export const visualNormalizationGoldenCases = [
  {
    name: 'setext heading',
    markdown: 'Heading\n=======\n',
    warning: 'Setext headings are rewritten as ATX headings',
  },
  {
    name: 'reference-style link',
    markdown: 'See [the method][method].\n\n[method]: https://example.com/method\n',
    warning: 'Reference-style links are inlined',
  },
  {
    name: 'compact list',
    markdown: '- Alpha\n- Beta\n',
    warning: 'Compact unordered lists are expanded',
  },
  {
    name: 'hard break',
    markdown: 'Hard break  \nnext line\n',
    warning: 'Trailing-space hard breaks are rewritten',
  },
];
